# Generated by Django 5.2 on 2025-05-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
        ("Services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voteblock",
            name="candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Accounts.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="voteblock",
            name="voter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Accounts.voter",
            ),
        ),
    ]
