# Generated by Django 5.2 on 2025-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Services", "0002_alter_voteblock_candidate_alter_voteblock_voter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
    ]
